# Generated by Django 4.2.3 on 2023-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Surname', models.CharField(max_length=30)),
                ('Patronymic', models.CharField(max_length=30)),
                ('Date_of_birth', models.DateTimeField()),
                ('Gender', models.CharField(max_length=15)),
                ('Photo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
