# Generated by Django 4.2.3 on 2023-07-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Профессии')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['-Date_of_birth'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='human',
            name='Date_of_birth',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='human',
            name='Gender',
            field=models.CharField(max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='human',
            name='Name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='Patronymic',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='human',
            name='Photo',
            field=models.ImageField(upload_to='media', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='human',
            name='Surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='human',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='New2.profession', verbose_name='Профессии'),
        ),
    ]
