# Generated by Django 4.2.3 on 2023-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New2', '0002_profession_alter_human_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Human',
            name='Name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
